# Generated by Django 3.1.1 on 2021-01-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=5)),
                ('sex', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
